<div align="center">
    <h1>Exploratory Data Analysis of Shark Attack Data</h1>
</div>

## Imports

In [466]:
import pandas as pd

%run "../utils/preprocessing/type_cleaner.py"
%run "../utils/preprocessing/activity_cleaner.py"
%run "../utils/preprocessing/gender_cleaner.py"
%run "../utils/preprocessing/age_cleaner.py"
%run "../utils/preprocessing/fatality_cleaner.py"
%run "../utils/preprocessing/time_cleaner.py"

## Dataset Contents

In [467]:
DATA = "../data/attacks.csv"

data_frame = pd.read_csv(
    DATA,
    encoding="latin1",
    usecols=[
        "Date", "Type", "Country", "Area", "Location", "Activity", "Sex ", "Age", "Fatal (Y/N)", "Time", "Species "
    ]
)

data_frame = data_frame.rename(
    columns={
        "Sex ": "Gender",
        "Fatal (Y/N)": "Fatal",
        "Species ": "Species"
    }
)

print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked     MEXICO           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location      Activity Gender  \
0                        Oceanside, San Diego County      Paddling      F
1                     St. Simon Island, Glynn County      Standing      F
2                                       Habush, Oahu       Surfing      M
3                                 Arrawarra Headland       Surfing      M
4                                           La Ticla   Free diving      M
5                                 Flat Rock, Ballina  Kite surfing      M
6                              Piedade Beach, Recife      Swimming      M
7  Lighhouse Point Park, Ponce Inlet, Volusia County       Fishing      M
8                       Cocoa Beach, Brevard  County       Walking      M
9                      Daytona Beach, Volusia County      Standing      M

       Age Fatal            Time          Species
0       57     N           18h00      White shark
1       11     N   14h00  -15h00          Unknown
2       48     N           07h45          Unknown
3  Unknown     N         Unknown        2 m shark
4  Unknown     N         Unknown  Tiger shark, 3m
5  Unknown     N         Unknown          Unknown
6       18     Y  Late afternoon      Tiger shark
7       52     N         Unknown  Lemon shark, 3'
8       15     N           17h00   Bull shark, 6'
9       12     N           14h00          Unknown

## Feature Engineering

### Before Preprocessing

In [469]:
data_frame.describe(include="all").T

         count unique                               top  freq
Date      6302   5433                              1957    11
Type      6298      8                        Unprovoked  4595
Country   6252    212                               USA  2229
Area      5847    825                           Florida  1037
Location  5762   4108  New Smyrna Beach, Volusia County   163
Activity  5758   1532                           Surfing   971
Gender    5737      6                                 M  5094
Age       3471    157                                17   154
Fatal     5763      8                                 N  4293
Time      2948    366                         Afternoon   187
Species   3464   1549                       White shark   163

### Cleaning Type Column

In [470]:
data_frame["Type"] = data_frame["Type"].apply(categorize_type)

In [471]:
data_frame["Type"].value_counts()

Type
Unprovoked      4595
Provoked         574
Invalid          547
Boating          341
Seadisaster      239
Questionable       2
Name: count, dtype: int64

### Cleaning Activity Column

In [472]:
data_frame["Activity"] = data_frame["Activity"].apply(categorize_activity)

Encountered unexpected string: "cleaning fish"
Encountered unexpected string: "touching a shark"
Encountered unexpected string: "photo shoot"
Encountered unexpected string: "kakaying"
Encountered unexpected string: "washing hands"
Encountered unexpected string: "lobstering"
Encountered unexpected string: "feeding stingrays?"
Encountered unexpected string: "photographing fish"
Encountered unexpected string: "playing in the water"
Encountered unexpected string: "playing"
Encountered unexpected string: "filming"
Encountered unexpected string: "feeding fish"
Encountered unexpected string: "playing with an air mattress"
Encountered unexpected string: "kneeling in the water"
Encountered unexpected string: "filming a documentary"
Encountered unexpected string: "cleaning fish"
Encountered unexpected string: "jumping in the waves"
Encountered unexpected string: "washing sand off a speared fish"
Encountered unexpected string: "wakeboarding"
Encountered unexpected string: "attempting to fix motor"
Encountered unexpected string: "rescuing"
Encountered unexpected string: "measuring sharks"
Encountered unexpected string: "washing his feet"
Encountered unexpected string: "crawling"
Encountered unexpected string: "feeding fish"
Encountered unexpected string: "removing fish from a trap"
Encountered unexpected string: "jumping"
Encountered unexpected string: "playing"
Encountered unexpected string: "jumped into the water"
Encountered unexpected string: "murder"
Encountered unexpected string: "reviving a sedated shark"
Encountered unexpected string: "playing on a sandbar"
Encountered unexpected string: "murder"
Encountered unexpected string: "playing soccer in the water"
Encountered unexpected string: "murder"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "touching sharks"
Encountered unexpected string: "playing"
Encountered unexpected string: "crouching in 2' of water"
Encountered unexpected string: "playing"
Encountered unexpected string: "jumping"
Encountered unexpected string: "jumping"
Encountered unexpected string: "unknown"
Encountered unexpected string: "hiking on the beach"
Encountered unexpected string: "batin"
Encountered unexpected string: "attempting to catch a crocodile"
Encountered unexpected string: "sinking of the 40' esperanza off st. maartin with 36 refugees on board"
Encountered unexpected string: "unknown"
Encountered unexpected string: "jumped into the water"
Encountered unexpected string: "conducting research"
Encountered unexpected string: "attempting to illegally enter the usa"
Encountered unexpected string: "jumping"
Encountered unexpected string: "playing"
Encountered unexpected string: "lying prone in 2' of water"
Encountered unexpected string: "scientific research (dr. sonny gruber's student)"
Encountered unexpected string: "cruising"
Encountered unexpected string: "splashing"
Encountered unexpected string: "unknown"
Encountered unexpected string: "watching seals"
Encountered unexpected string: "attempting to attract dolphins"
Encountered unexpected string: "boeing 757 enroute from porta plata plunged into the sea"
Encountered unexpected string: "on a float"
Encountered unexpected string: ""riding waves on a board""
Encountered unexpected string: "playing / jumping"
Encountered unexpected string: "murder victim"
Encountered unexpected string: "jumped off rocks into white water"
Encountered unexpected string: "playing volleyball with friends"
Encountered unexpected string: "stamding"
Encountered unexpected string: "riding floatation device"
Encountered unexpected string: "playing"
Encountered unexpected string: "preparing to fish for jack-mackerel"
Encountered unexpected string: "feeding fish"
Encountered unexpected string: "playing"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "the mv dona marilyn sank in typhoon unsang with the loss of 389 lives"
Encountered unexpected string: "sittting in water with his child"
Encountered unexpected string: "pêcheur de bichiques"
Encountered unexpected string: "returning to shore, collided with shark"
Encountered unexpected string: "dropping anchor"
Encountered unexpected string: "the inter-island ferry vula sank in heavy weather"
Encountered unexpected string: "jumped into the water from a cliff"
Encountered unexpected string: "nsb meshing"
Encountered unexpected string: "racing ski"
Encountered unexpected string: "playing in knee-deep water"
Encountered unexpected string: "towing her sister on plastic ski board"
Encountered unexpected string: "murder"
Encountered unexpected string: "steinhart aquarium"
Encountered unexpected string: "ran into the water"
Encountered unexpected string: "in waist-deep water"
Encountered unexpected string: "foundering of the israeli freighter mezada"
Encountered unexpected string: "exercising his dog in the shallows"
Encountered unexpected string: "resting on body board"
Encountered unexpected string: "murdered by thai pirates"
Encountered unexpected string: "their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days"
Encountered unexpected string: "their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days"
Encountered unexpected string: "their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days"
Encountered unexpected string: "thrashing the water / imitating the shark victim from "jaws""
Encountered unexpected string: "3,909-ton panamanian freighter chieh lee sank in a typhoon"
Encountered unexpected string: "playing"
Encountered unexpected string: "attempted to return injured shark to the sea"
Encountered unexpected string: "washing cooking pans"
Encountered unexpected string: "washing clothes on stairs"
Encountered unexpected string: "sight-seeing"
Encountered unexpected string: "playing with a frisbee in the shallows"
Encountered unexpected string: "leaving the water"
Encountered unexpected string: "schooner sank during a storm"
Encountered unexpected string: "sinking of the m/v mindoro during a typhoon"
Encountered unexpected string: "vehicle plunged over cliff into the water"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "splashing"
Encountered unexpected string: "attacked shark with fists"
Encountered unexpected string: "sinking of the dredge world atlas"
Encountered unexpected string: "overturned skiff"
Encountered unexpected string: "colombian  (avianca) dc-4 airliner plunged into the sea 5 minutes after takeoff"
Encountered unexpected string: "jumped into the water"
Encountered unexpected string: "argentine air force c-54"
Encountered unexpected string: "playing in the water"
Encountered unexpected string: "arsinoe, a french tanker"
Encountered unexpected string: "filming underwater, carrying powerhead"
Encountered unexpected string: "searching for remains of  dr. marais"
Encountered unexpected string: "conducting a promotional film project for the gemini space program (a practice astronaut recovery)"
Encountered unexpected string: "attempting to swim across the atlantic ocean"
Encountered unexpected string: "lying in 2 feet of water"
Encountered unexpected string: "testing anti-shark cage"
Encountered unexpected string: "washed into sea while picking opihi"
Encountered unexpected string: "the 500-ton coastal trader polurrian foundered"
Encountered unexpected string: "s.s. marine sulphur queen, laden with molten sulphur was bound from beaumont, texas for norfolk, va, when she disappeared with 39 on board"
Encountered unexpected string: "u.s. airforce crewman reported missing after bailing out of jet"
Encountered unexpected string: "escaping from alacatraz"
Encountered unexpected string: "escaping from alacatraz"
Encountered unexpected string: "escaping from alacatraz"
Encountered unexpected string: "washing"
Encountered unexpected string: "25-foot cabin cruiser happy jack sank in heavy seas"
Encountered unexpected string: "splashing"
Encountered unexpected string: "gathering shells"
Encountered unexpected string: "attaching a line at sea"
Encountered unexpected string: "splashing"
Encountered unexpected string: "cleaning a tank"
Encountered unexpected string: "pacific seafarer of us navy"
Encountered unexpected string: "ocean racing"
Encountered unexpected string: "hand lining for shad"
Encountered unexpected string: "testing classified underwater electronic gear for raytheon corporation, vessel torn apart by explosion"
Encountered unexpected string: "speared a grouper, saw shark but it came for him instead of the fish so he fired spear into sharks mouth. then shark took grouper but unable to swallow because of the spear in its mouth."
Encountered unexpected string: "s2f-1 airplane crashed immediately after carrier take-off"
Encountered unexpected string: "setting crayfish pots"
Encountered unexpected string: "gigging for flounder"
Encountered unexpected string: "pulling anchor"
Encountered unexpected string: "columbian petrol barge rio atrato burned and sank"
Encountered unexpected string: "dragging banana seeds through the shallows"
Encountered unexpected string: "placed hand in disemboweled sharks jaws"
Encountered unexpected string: "m.v. tropical sank. sole survivor rode oil drums for 8 days without food or water."
Encountered unexpected string: "attempting to set underwater endurance record"
Encountered unexpected string: "ocean racing"
Encountered unexpected string: "crossing the bay at the ford"
Encountered unexpected string: "crouching in the water"
Encountered unexpected string: "aircaft exploded"
Encountered unexpected string: "washing"
Encountered unexpected string: "went to aid of child being menaced by the shark"
Encountered unexpected string: "swept off deck of s.s.frontenac enroute from west indies to us"
Encountered unexpected string: "survived crash of two-engine  c-46 transport plane carrying 62 migrant workers from puerto rico to usa"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "suicide"
Encountered unexpected string: "defecating in water beneath the docks"
Encountered unexpected string: "bending over"
Encountered unexpected string: "no details"
Encountered unexpected string: "lifesaving exhibition"
Encountered unexpected string: "leicester abandoned in a hurricane"
Encountered unexpected string: "underwater photography"
Encountered unexpected string: "jumping in swells"
Encountered unexpected string: "90 european civilians, many women & children, were placed on the deck of a japanese submarine that submerged when it was well offshore"
Encountered unexpected string: "parachuted into pacific"
Encountered unexpected string: "the 6711-ton american freighter & troop transport cape san juan was torpedoed by the japanese submarine i-21"
Encountered unexpected string: "known as the battle of the bismarck sea :  8 japanese destroyers guarding a convoy of 8 transports were attacked by 129 allied fighters, 207 bombers & 3 squadrons of the royal australian air force."
Encountered unexpected string: "the uss wahoo torpedoes & sank the japanese troop transport buyo maru"
Encountered unexpected string: "thrown from destroyer when shell hit"
Encountered unexpected string: "explosion & sinking of the uss juneau after being torpedoed by the submarine  i-85"
Encountered unexpected string: "esso bolivar was torpedoed & shelled by the german submarine u-126"
Encountered unexpected string: "captured allied soldiers were squeezed into 3' bamboo pig baskets & fed to waiting sharks"
Encountered unexpected string: "torpedoed & burning british  light cruiser with a crew of 450 men"
Encountered unexpected string: "ss ethel skakel foundered in central america hurricane of 1941"
Encountered unexpected string: "male"
Encountered unexpected string: "japanese freighter bokuyo maru burned & sank"
Encountered unexpected string: "washed off freighter huncliff by a freak wave"
Encountered unexpected string: "scooping prawns"
Encountered unexpected string: "the schooner elizabeth, bound from bluefields, nicaragua to the river port of san carlos foundered"
Encountered unexpected string: "tzenny chandris, a greek freighter laden with scrap iron, foundered in heavy weather"
Encountered unexpected string: "cruising"
Encountered unexpected string: "disappeared 11 days earlier, probable homicide victim"
Encountered unexpected string: "splashing"
Encountered unexpected string: "splashing in water"
Encountered unexpected string: "hurricane & tidal wave"
Encountered unexpected string: "working near fish traps"
Encountered unexpected string: "retrieving meat from a cage in the water"
Encountered unexpected string: "the steamer tahiti collided with the ferry greycliffe"
Encountered unexpected string: "italian liner principessa mafalda sank"
Encountered unexpected string: "riding horseback across the creek"
Encountered unexpected string: "attempting to rescue drowning man"
Encountered unexpected string: "jumped into the water"
Encountered unexpected string: "dry shelling"
Encountered unexpected string: "seaplane columbus ditched in the sea"
Encountered unexpected string: "splashing"
Encountered unexpected string: "knocked into the water"
Encountered unexpected string: "taking wife to beach & about 1 m from the shore"
Encountered unexpected string: "washing clothes"
Encountered unexpected string: "3-masted steel barque glenbank foundered during a cyclone"
Encountered unexpected string: "reported swept away by waves while gathering opihi"
Encountered unexpected string: "on december 28, 1908, an earthquake, followed by tsunamis, destroyed coastal towns in silcily and southern italy, killing more than 100,000 people"
Encountered unexpected string: "the 168-ton belmore foundered in heavy seas"
Encountered unexpected string: "the british steamer caribbee foundered"
Encountered unexpected string: "."
Encountered unexpected string: "."
Encountered unexpected string: "shooting sharks"
Encountered unexpected string: "the schooner tahitienne foundered in a hurricane"
Encountered unexpected string: "."
Encountered unexpected string: "washing horses"
Encountered unexpected string: "human head found in shark caught by british steamer syria"
Encountered unexpected string: "harpooning turtles"
Encountered unexpected string: "suicide"
Encountered unexpected string: "taking catch from a fish weir in which the shark was snared"
Encountered unexpected string: "the cutter francis adams foundered"
Encountered unexpected string: "trailing hand in the water"
Encountered unexpected string: "loss of the schooner nomad"
Encountered unexpected string: ""crossing the river""
Encountered unexpected string: "murder"
Encountered unexpected string: "hms victoria collided with the hms camperdown"
Encountered unexpected string: "his balloon crashed in the harbor"
Encountered unexpected string: "murdered"
Encountered unexpected string: "riding a horse"
Encountered unexpected string: "shooting sharks"
Encountered unexpected string: "fleeing across a river"
Encountered unexpected string: "parachuted from balloon"
Encountered unexpected string: "probabable drowning"
Encountered unexpected string: "the dwarka foundered"
Encountered unexpected string: "crossing the river mouth"
Encountered unexpected string: "escaping from blackbirding vessel"
Encountered unexpected string: "burning of the s.s. missouri"
Encountered unexpected string: "suicide"
Encountered unexpected string: "a junk foundered"
Encountered unexpected string: "coming ashore on a hawser"
Encountered unexpected string: "reaching for life preserver"
Encountered unexpected string: "trying to catch a wounded bird"
Encountered unexpected string: "deserting the bark nazarene"
Encountered unexpected string: "hilo"
Encountered unexpected string: "jumped into river"
Encountered unexpected string: "unknown, but it was said to be the "first known attack in sydney harbour""
Encountered unexpected string: "washing his feet"
Encountered unexpected string: "hooking into a whale"
Encountered unexpected string: "washing a dog"
Encountered unexpected string: "hbm magpie foundered in a squall"
Encountered unexpected string: "washing himself"
Encountered unexpected string: "murder"
Encountered unexpected string: "washing his pig in preparation for a religious ceremony"

In [473]:
data_frame["Activity"].value_counts()

Activity
Surfing                    1347
Swimming                   1206
Fishing                    1145
Diving                      497
Maritime Disaster           356
Boating                     349
Wading in Shallow Water     300
Other                       254
Interacting with Sharks     118
Snorkeling                   93
Floating/Treading Water      93
Name: count, dtype: int64

### Cleaning Gender Column

In [474]:
data_frame["Gender"] = data_frame["Gender"].apply(categorize_gender)

Encountered unexpected string: "LLI"
Encountered unexpected string: "."

In [475]:
data_frame["Gender"].value_counts()

Gender
M    5098
F     637
Name: count, dtype: int64

### Cleaning Age Column

In [476]:
data_frame["Age"] = data_frame["Age"].apply(categorize_age)

Encountered unexpected string: "  "
Encountered unexpected string: "elderly"
Encountered unexpected string: "adult"
Encountered unexpected string: "(adult)"
Encountered unexpected string: "x"
Encountered unexpected string: ""middle-age""
Encountered unexpected string: "make line green"
Encountered unexpected string: ""young""
Encountered unexpected string: "f"
Encountered unexpected string: "young"
Encountered unexpected string: "a.m."
Encountered unexpected string: "young"

In [477]:
data_frame["Age"].value_counts()

Age
17.0    155
16.0    154
18.0    150
19.0    145
20.0    145
       ...
84.0      1
87.0      1
67.0      1
81.0      1
2.0       1
Name: count, Length: 81, dtype: int64

### Cleaning Fatality Column

In [478]:
data_frame["Fatal"] = data_frame["Fatal"].apply(categorize_fatality)

Encountered unexpected string: "2017"

In [479]:
data_frame["Fatal"].value_counts()

Fatal
N    4302
Y    1389
Name: count, dtype: int64

### Cleaning Time Column

In [480]:
data_frame["Time"] = data_frame["Time"].apply(categorize_time)

Encountered improper time string: "2 hours after Opperman".
Encountered improper time string: "FATAL  (Wire netting installed at local beaches after this incident.)".

In [481]:
data_frame["Time"].value_counts()

Time
Afternoon    1387
Morning       949
Evening       477
Night         122
Name: count, dtype: int64

## Summary

### After Preprocessing

In [482]:
print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked     MEXICO           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location                 Activity  \
0                        Oceanside, San Diego County                  Surfing
1                     St. Simon Island, Glynn County  Wading in Shallow Water
2                                       Habush, Oahu                  Surfing
3                                 Arrawarra Headland                  Surfing
4                                           La Ticla                   Diving
5                                 Flat Rock, Ballina                  Surfing
6                              Piedade Beach, Recife                 Swimming
7  Lighhouse Point Park, Ponce Inlet, Volusia County                  Fishing
8                       Cocoa Beach, Brevard  County  Wading in Shallow Water
9                      Daytona Beach, Volusia County  Wading in Shallow Water

  Gender      Age Fatal       Time          Species
0      F     57.0     N    Evening      White shark
1      F     11.0     N  Afternoon          Unknown
2      M     48.0     N    Morning          Unknown
3      M  Unknown     N    Unknown        2 m shark
4      M  Unknown     N    Unknown  Tiger shark, 3m
5      M  Unknown     N    Unknown          Unknown
6      M     18.0     Y  Afternoon      Tiger shark
7      M     52.0     N    Unknown  Lemon shark, 3'
8      M     15.0     N    Evening   Bull shark, 6'
9      M     12.0     N  Afternoon          Unknown

In [483]:
data_frame.describe(include="all").T.fillna("—")

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Date,6302,5433,1957,11,—,—,—,—,—,—,—
Type,6298,6,Unprovoked,4595,—,—,—,—,—,—,—
Country,6252,212,USA,2229,—,—,—,—,—,—,—
Area,5847,825,Florida,1037,—,—,—,—,—,—,—
Location,5762,4108,"New Smyrna Beach, Volusia County",163,—,—,—,—,—,—,—
Activity,5758,11,Surfing,1347,—,—,—,—,—,—,—
Gender,5735,2,M,5098,—,—,—,—,—,—,—
Age,3456.0,—,—,—,27.291088,13.897882,1.0,17.0,24.0,35.0,87.0
Fatal,5691,2,N,4302,—,—,—,—,—,—,—
Time,2935,4,Afternoon,1387,—,—,—,—,—,—,—
Species,3464,1549,White shark,163,—,—,—,—,—,—,—