<div align="center">
    <h1>Exploratory Data Analysis of Shark Attack Data</h1>
</div>

## Imports

In [37]:
import pandas as pd

%run "../server/utils/preprocessing/type_cleaner.py"
%run "../server/utils/preprocessing/activity_cleaner.py"
%run "../server/utils/preprocessing/gender_cleaner.py"
%run "../server/utils/preprocessing/age_cleaner.py"
%run "../server/utils/preprocessing/fatality_cleaner.py"
%run "../server/utils/preprocessing/time_cleaner.py"
%run "../server/utils/preprocessing/species_cleaner.py"

## Dataset Contents

In [38]:
DATA_PATH = "../server/data/attacks.csv"

data_frame = pd.read_csv(
    DATA_PATH,
    encoding="latin1",
    usecols=[
        "Date", "Type", "Country", "Area", "Location", "Activity", "Sex ", "Age", "Fatal (Y/N)", "Time", "Species "
    ]
)

data_frame = data_frame.rename(
    columns={
        "Sex ": "Gender",
        "Fatal (Y/N)": "Fatal",
        "Species ": "Species"
    }
)

print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked     MEXICO           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location      Activity Gender  \
0                        Oceanside, San Diego County      Paddling      F
1                     St. Simon Island, Glynn County      Standing      F
2                                       Habush, Oahu       Surfing      M
3                                 Arrawarra Headland       Surfing      M
4                                           La Ticla   Free diving      M
5                                 Flat Rock, Ballina  Kite surfing      M
6                              Piedade Beach, Recife      Swimming      M
7  Lighhouse Point Park, Ponce Inlet, Volusia County       Fishing      M
8                       Cocoa Beach, Brevard  County       Walking      M
9                      Daytona Beach, Volusia County      Standing      M

       Age Fatal            Time          Species
0       57     N           18h00      White shark
1       11     N   14h00  -15h00          Unknown
2       48     N           07h45          Unknown
3  Unknown     N         Unknown        2 m shark
4  Unknown     N         Unknown  Tiger shark, 3m
5  Unknown     N         Unknown          Unknown
6       18     Y  Late afternoon      Tiger shark
7       52     N         Unknown  Lemon shark, 3'
8       15     N           17h00   Bull shark, 6'
9       12     N           14h00          Unknown

## Feature Engineering

### Before Preprocessing

In [39]:
data_frame.describe(include="all").T

         count unique                               top  freq
Date      6302   5433                              1957    11
Type      6298      8                        Unprovoked  4595
Country   6252    212                               USA  2229
Area      5847    825                           Florida  1037
Location  5762   4108  New Smyrna Beach, Volusia County   163
Activity  5758   1532                           Surfing   971
Gender    5737      6                                 M  5094
Age       3471    157                                17   154
Fatal     5763      8                                 N  4293
Time      2948    366                         Afternoon   187
Species   3464   1549                       White shark   163

### Cleaning Date Column

In [40]:
data_frame["Date"].value_counts()

Date
1957                                                                11
1942                                                                 9
1956                                                                 8
1958                                                                 7
1950                                                                 7
                                                                    ..
No date (3 days after preceding incident) & prior to 19-Jul-1913     1
Before 19-Jul-1913                                                   1
1900-1905                                                            1
1883-1889                                                            1
1845-1853                                                            1
Name: count, Length: 5433, dtype: int64

### Cleaning Type Column

In [41]:
data_frame["Type"] = data_frame["Type"].apply(categorize_type)

In [42]:
data_frame["Type"].value_counts()

Type
Unprovoked      4595
Provoked         574
Invalid          547
Boating          341
Sea Disaster     239
Questionable       2
Name: count, dtype: int64

### Cleaning Country Column

In [43]:
data_frame["Country"].value_counts()

Country
USA                   2229
AUSTRALIA             1338
SOUTH AFRICA           579
PAPUA NEW GUINEA       134
NEW ZEALAND            128
                      ...
BAHREIN                  1
KOREA                    1
RED SEA?                 1
ASIA?                    1
CEYLON (SRI LANKA)       1
Name: count, Length: 212, dtype: int64

### Cleaning Area Column

In [44]:
data_frame["Area"].value_counts()

Area
Florida                              1037
New South Wales                       486
Queensland                            311
Hawaii                                298
California                            290
                                     ...
Riau Province                           1
Bikini Atoll                            1
Between New Ireland & New Britain       1
Ba Ria-Vung Tau  Province               1
Moala Island                            1
Name: count, Length: 825, dtype: int64

### Cleaning Location Columns

In [45]:
data_frame["Location"].value_counts()

Location
New Smyrna Beach, Volusia County       163
Daytona Beach, Volusia County           30
Ponce Inlet, Volusia County             20
Melbourne Beach, Brevard County         18
Myrtle Beach, Horry County              17
                                      ...
                                         1
Roebuck Bay                              1
Ocracoke Inlet                           1
Panama Bay 8ºN, 79ºW                     1
Below the English fort, Trincomalee      1
Name: count, Length: 4108, dtype: int64

### Cleaning Activity Column

In [46]:
data_frame["Activity"] = data_frame["Activity"].apply(categorize_activity)

Encountered unexpected string: "paddle-skiing"
Encountered unexpected string: "cleaning fish"
Encountered unexpected string: "touching a shark"
Encountered unexpected string: "photo shoot"
Encountered unexpected string: "kakaying"
Encountered unexpected string: "washing hands"
Encountered unexpected string: "lobstering"
Encountered unexpected string: "feeding stingrays?"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "photographing fish"
Encountered unexpected string: "playing in the water"
Encountered unexpected string: "playing"
Encountered unexpected string: "filming"
Encountered unexpected string: "feeding fish"
Encountered unexpected string: "playing with an air mattress"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "kneeling in the water"
Encountered unexpected string: "fell into the water"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "filming a documentary"
Encountered unexpected string: "cleaning fish"
Encountered unexpected string: "jumping in the waves"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "washing sand off a speared fish"
Encountered unexpected string: "wakeboarding"
Encountered unexpected string: "attempting to fix motor"
Encountered unexpected string: "rescuing"
Encountered unexpected string: "measuring sharks"
Encountered unexpected string: "washing his feet"
Encountered unexpected string: "crawling"
Encountered unexpected string: "feeding fish"
Encountered unexpected string: "air disaster"
Encountered unexpected string: "sinking of the cargo ship mark jason"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "removing fish from a trap"
Encountered unexpected string: "the 426-ton cargo ship mia, laden with cement, capsized in heavy seas"
Encountered unexpected string: "jumping"
Encountered unexpected string: "playing"
Encountered unexpected string: "jumped into the water"
Encountered unexpected string: "murder"
Encountered unexpected string: "reviving a sedated shark"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "playing on a sandbar"
Encountered unexpected string: "murder"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "playing soccer in the water"
Encountered unexpected string: "murder"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "touching sharks"
Encountered unexpected string: "playing"
Encountered unexpected string: "crouching in 2' of water"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "swept out to sea by the tsunami, she clung  to a log for 24 hours"
Encountered unexpected string: "playing"
Encountered unexpected string: "jumping"
Encountered unexpected string: "air disaster. flash airlines boeing 737 crashed into the red sea"
Encountered unexpected string: "jumping"
Encountered unexpected string: "unknown"
Encountered unexpected string: "hiking on the beach"
Encountered unexpected string: "batin"
Encountered unexpected string: "attempting to catch a crocodile"
Encountered unexpected string: "unknown"
Encountered unexpected string: "shipwrecked"
Encountered unexpected string: "fell onto dead shark"
Encountered unexpected string: "jumped into the water"
Encountered unexpected string: "conducting research"
Encountered unexpected string: "attempting to illegally enter the usa"
Encountered unexpected string: "jumping"
Encountered unexpected string: "playing"
Encountered unexpected string: "lying prone in 2' of water"
Encountered unexpected string: "adrift in a life jacket"
Encountered unexpected string: "scientific research (dr. sonny gruber's student)"
Encountered unexpected string: "cruising"
Encountered unexpected string: "paddle skiing"
Encountered unexpected string: "splashing"
Encountered unexpected string: "unknown"
Encountered unexpected string: "watching seals"
Encountered unexpected string: "attempting to attract dolphins"
Encountered unexpected string: "boeing 757 enroute from porta plata plunged into the sea"
Encountered unexpected string: "on a float"
Encountered unexpected string: ""riding waves on a board""
Encountered unexpected string: "playing / jumping"
Encountered unexpected string: "murder victim"
Encountered unexpected string: "jumped off rocks into white water"
Encountered unexpected string: "playing volleyball with friends"
Encountered unexpected string: "stamding"
Encountered unexpected string: "riding floatation device"
Encountered unexpected string: "playing"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "preparing to fish for jack-mackerel"
Encountered unexpected string: "feeding fish"
Encountered unexpected string: "playing"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "the mv dona marilyn sank in typhoon unsang with the loss of 389 lives"
Encountered unexpected string: "sittting in water with his child"
Encountered unexpected string: "pêcheur de bichiques"
Encountered unexpected string: "returning to shore, collided with shark"
Encountered unexpected string: "vessel caught fire & capsized, survivors in the water"
Encountered unexpected string: "dropping anchor"
Encountered unexpected string: "the inter-island ferry vula sank in heavy weather"
Encountered unexpected string: "jumped into the water from a cliff"
Encountered unexpected string: "adrift after ditching plane in the sea"
Encountered unexpected string: "nsb meshing"
Encountered unexpected string: "racing ski"
Encountered unexpected string: "playing in knee-deep water"
Encountered unexpected string: "sea disaster, foundering of the cargo vessle m/v dorolonda"
Encountered unexpected string: "towing her sister on plastic ski board"
Encountered unexpected string: "murder"
Encountered unexpected string: "steinhart aquarium"
Encountered unexpected string: "14 m prawn trawler new venture capsized  & sank in heavy seas three people in the water"
Encountered unexpected string: "ran into the water"
Encountered unexpected string: "in waist-deep water"
Encountered unexpected string: "sailboarding, fell into water 100 yards outside the breakwater"
Encountered unexpected string: "16' catamaran capsized previous night, occupants stayed with wreckage until morning, then attempted to swim ashore"
Encountered unexpected string: "foundering of the israeli freighter mezada"
Encountered unexpected string: "exercising his dog in the shallows"
Encountered unexpected string: "resting on body board"
Encountered unexpected string: "murdered by thai pirates"
Encountered unexpected string: "their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days"
Encountered unexpected string: "their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days"
Encountered unexpected string: "their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days"
Encountered unexpected string: "thrashing the water / imitating the shark victim from "jaws""
Encountered unexpected string: "shipwreck"
Encountered unexpected string: "3,909-ton panamanian freighter chieh lee sank in a typhoon"
Encountered unexpected string: "playing"
Encountered unexpected string: "sea disaster"
Encountered unexpected string: "ferry capsized"
Encountered unexpected string: "wreck of the 1689-ton portuguese  coaster angoche"
Encountered unexpected string: "shipwreck"
Encountered unexpected string: "air disaster"
Encountered unexpected string: "attempted to return injured shark to the sea"
Encountered unexpected string: "washing cooking pans"
Encountered unexpected string: "washing clothes on stairs"
Encountered unexpected string: "sight-seeing"
Encountered unexpected string: "wreck of the storm king"
Encountered unexpected string: "playing with a frisbee in the shallows"
Encountered unexpected string: "leaving the water"
Encountered unexpected string: "schooner sank during a storm"
Encountered unexpected string: "sinking of the m/v mindoro during a typhoon"
Encountered unexpected string: "vehicle plunged over cliff into the water"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "splashing"
Encountered unexpected string: "attacked shark with fists"
Encountered unexpected string: "sinking of the dredge world atlas"
Encountered unexpected string: "shipwreck"
Encountered unexpected string: "the passenger ship pioneer cebu  capsized & sank in typhoon irma"
Encountered unexpected string: "overturned skiff"
Encountered unexpected string: "wreck of the state oil company ship permina"
Encountered unexpected string: "colombian  (avianca) dc-4 airliner plunged into the sea 5 minutes after takeoff"
Encountered unexpected string: "jumped into the water"
Encountered unexpected string: "argentine air force c-54"
Encountered unexpected string: "playing in the water"
Encountered unexpected string: "arsinoe, a french tanker"
Encountered unexpected string: "filming underwater, carrying powerhead"
Encountered unexpected string: "searching for remains of  dr. marais"
Encountered unexpected string: "conducting a promotional film project for the gemini space program (a practice astronaut recovery)"
Encountered unexpected string: "attempting to swim across the atlantic ocean"
Encountered unexpected string: "lying in 2 feet of water"
Encountered unexpected string: "greek steamship lakonia caught fire, 98 of her 646 passengers, and 30 of her crew of 376 perished"
Encountered unexpected string: "testing anti-shark cage"
Encountered unexpected string: "washed into sea while picking opihi"
Encountered unexpected string: "the 500-ton coastal trader polurrian foundered"
Encountered unexpected string: "abandoning burning ship captain george in raging seas"
Encountered unexpected string: "adrift after wave swamped engine"
Encountered unexpected string: "u.s. airforce crewman reported missing after bailing out of jet"
Encountered unexpected string: "escaping from alacatraz"
Encountered unexpected string: "escaping from alacatraz"
Encountered unexpected string: "escaping from alacatraz"
Encountered unexpected string: "washing"
Encountered unexpected string: "25-foot cabin cruiser happy jack sank in heavy seas"
Encountered unexpected string: "splashing"
Encountered unexpected string: "gathering shells"
Encountered unexpected string: "attaching a line at sea"
Encountered unexpected string: "splashing"
Encountered unexpected string: "checking fish traps, fell into the water"
Encountered unexpected string: "cargo ship dara sank after collision with another ship during a severe storm"
Encountered unexpected string: "cleaning a tank"
Encountered unexpected string: "pacific seafarer of us navy"
Encountered unexpected string: "ocean racing"
Encountered unexpected string: "fell overboard, prop slashed arm"
Encountered unexpected string: "hand lining for shad"
Encountered unexpected string: "cargo ship el gamil entroute suez to yemen (aden) when her cargo shifted and she sank. 19 egyption sailors jumped into the water and swam for several hours before being bitten by sharks"
Encountered unexpected string: "testing classified underwater electronic gear for raytheon corporation, vessel torn apart by explosion"
Encountered unexpected string: "speared a grouper, saw shark but it came for him instead of the fish so he fired spear into sharks mouth. then shark took grouper but unable to swallow because of the spear in its mouth."
Encountered unexpected string: "s2f-1 airplane crashed immediately after carrier take-off"
Encountered unexpected string: "setting crayfish pots"
Encountered unexpected string: "ship m.v. rizal sank during typhoon"
Encountered unexpected string: "adrift, hanging onto cushion, after his 17' skiff ran out of gas & capsized 3 miles from shore"
Encountered unexpected string: "gigging for flounder"
Encountered unexpected string: "pulling anchor"
Encountered unexpected string: "columbian petrol barge rio atrato burned and sank"
Encountered unexpected string: "jumped overboard to rescue a man"
Encountered unexpected string: "washed overboard into school of fish"
Encountered unexpected string: "in deep water about 100 yards from his ship"
Encountered unexpected string: "dragging banana seeds through the shallows"
Encountered unexpected string: "cleaning hull of ship"
Encountered unexpected string: ""climbing up to ship after repairing the stern in water""
Encountered unexpected string: "placed hand in disemboweled sharks jaws"
Encountered unexpected string: "air/sea disaster pan-american airlines stratocruiser with 44 people onboard crashed into the sea"
Encountered unexpected string: "m.v. tropical sank. sole survivor rode oil drums for 8 days without food or water."
Encountered unexpected string: "climbing back on ship"
Encountered unexpected string: "air/sea disaster"
Encountered unexpected string: "attempting to set underwater endurance record"
Encountered unexpected string: "shipwreck"
Encountered unexpected string: "ocean racing"
Encountered unexpected string: ""flying tiger" transport plane went down with 5 men onboard"
Encountered unexpected string: ""flying tiger" transport plane went down with 5 men onboard"
Encountered unexpected string: "crossing the bay at the ford"
Encountered unexpected string: "crouching in the water"
Encountered unexpected string: "aircaft exploded"
Encountered unexpected string: "accidentally dragged overboard from the sampan holokahana into school of yellowfin tuna"
Encountered unexpected string: "retrieving bait box that had fallen overboard"
Encountered unexpected string: "washing"
Encountered unexpected string: "air disaster"
Encountered unexpected string: "went to aid of child being menaced by the shark"
Encountered unexpected string: "cargo ship southern isle sank at 04h00"
Encountered unexpected string: "fell overboard"
Encountered unexpected string: "swept off deck of s.s.frontenac enroute from west indies to us"
Encountered unexpected string: "survived crash of two-engine  c-46 transport plane carrying 62 migrant workers from puerto rico to usa"
Encountered unexpected string: "lifesaving drill"
Encountered unexpected string: "suicide"
Encountered unexpected string: "defecating in water beneath the docks"
Encountered unexpected string: "bending over"
Encountered unexpected string: "sea disaster, sinking of the motorship wingate"
Encountered unexpected string: "no details"
Encountered unexpected string: "lifesaving exhibition"
Encountered unexpected string: "2 messboys (jeppsen) & tony latona (13) were playing on the afterdeck of the danish ship grete maersk. jeppsen fell overboard, latona threw a lifebelt then jumped in to help him. ship didnt notice they were missing"
Encountered unexpected string: "leicester abandoned in a hurricane"
Encountered unexpected string: "underwater photography"
Encountered unexpected string: "jumped overboard"
Encountered unexpected string: "jumping in swells"
Encountered unexpected string: "bitten after dhow shipwrecked"
Encountered unexpected string: "american cruiser indianapolis torpedoed & sunk by the japanese submarine i-58"
Encountered unexpected string: "90 european civilians, many women & children, were placed on the deck of a japanese submarine that submerged when it was well offshore"
Encountered unexpected string: "playing on rock, slipped & fell into the water"
Encountered unexpected string: "uss gambier bay cve-73  shelled & sunk  at 09h57 on 10/24/1944, by japanes fleet enroute to attack the allied landing force at leyte."
Encountered unexpected string: "parachuted into pacific"
Encountered unexpected string: "washed overboard by swell"
Encountered unexpected string: "fell overboard from uss ward"
Encountered unexpected string: "the cuban freighter libertad was torpedoed and sunk by the german submarine u-129"
Encountered unexpected string: "the 6711-ton american freighter & troop transport cape san juan was torpedoed by the japanese submarine i-21"
Encountered unexpected string: "s2n navy scout plane went down, e.h. almond & lieut a.g. reading in water"
Encountered unexpected string: "s2n navy scout plane went down, e.h. almond & lieut a.g. reading in water"
Encountered unexpected string: "hospital ship centaur torpedoed & sunk by the japanese submarine i-177"
Encountered unexpected string: "ship torpedoed 400 miles off the african coas. man was clinging to hatch cover"
Encountered unexpected string: "the 21,516-ton troopship empress of canada torpedoed and sunk by the italian submarine leonardo da vinci"
Encountered unexpected string: "the 3540-ton alfonso penna was torpedoed & sunk by the italian submarine barbarigo"
Encountered unexpected string: "known as the battle of the bismarck sea :  8 japanese destroyers guarding a convoy of 8 transports were attacked by 129 allied fighters, 207 bombers & 3 squadrons of the royal australian air force."
Encountered unexpected string: "the uss wahoo torpedoes & sank the japanese troop transport buyo maru"
Encountered unexpected string: "u-177 torpedoed & sank the troopship nova scotia"
Encountered unexpected string: "thrown from destroyer when shell hit"
Encountered unexpected string: "explosion & sinking of the uss juneau after being torpedoed by the submarine  i-85"
Encountered unexpected string: "his ship, the us destroyer duncan dd 485, had been  sunk by crossfire from japanese warships. he was wearing a kapok lifejacket & using 2 aluminum powder tins for floatation"
Encountered unexpected string: "the 6015-ton british ship empire avocet was torpedoed by the german submarine u-125."
Encountered unexpected string: "the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942."
Encountered unexpected string: "a 210-ton brig was sunk by a japanese submarine. some of the survivors were machine-gunned & some were taken by sharks"
Encountered unexpected string: "esso bolivar was torpedoed & shelled by the german submarine u-126"
Encountered unexpected string: "captured allied soldiers were squeezed into 3' bamboo pig baskets & fed to waiting sharks"
Encountered unexpected string: "jumped overboard from torpedoed panamanian freighter"
Encountered unexpected string: "torpedoed & burning british  light cruiser with a crew of 450 men"
Encountered unexpected string: "hmas parramatta torpedoed & sunk by the u-559"
Encountered unexpected string: "hmas parramatta torpedoed & sunk by the u-559"
Encountered unexpected string: "british cruiser dunedin torpedoed & sunk by the u-124"
Encountered unexpected string: "german raider kormoran was sunk in an engagement with hmas sydney"
Encountered unexpected string: "ss ethel skakel foundered in central america hurricane of 1941"
Encountered unexpected string: "the troopship britannia was sunk by the german raider thor"
Encountered unexpected string: "rescuing seaman after ship sunk by german raider"
Encountered unexpected string: "slipped off rocks and fell into the water"
Encountered unexpected string: "male"
Encountered unexpected string: "japanese freighter bokuyo maru burned & sank"
Encountered unexpected string: "washed off freighter huncliff by a freak wave"
Encountered unexpected string: "scooping prawns"
Encountered unexpected string: "she was on a ship that was torpedoes & was in the water awaiting rescue"
Encountered unexpected string: "the schooner elizabeth, bound from bluefields, nicaragua to the river port of san carlos foundered"
Encountered unexpected string: "tzenny chandris, a greek freighter laden with scrap iron, foundered in heavy weather"
Encountered unexpected string: "wreck of a sampam"
Encountered unexpected string: "swept overboard"
Encountered unexpected string: "cruising"

In [47]:
data_frame["Activity"].value_counts()

Activity
Surfing                    1384
Swimming                   1226
Fishing                    1160
Diving                      505
Other                       482
Boating                     363
Wading in Shallow Water     302
Floating/Treading Water     125
Interacting with Sharks     118
Snorkeling                   93
Name: count, dtype: int64

### Cleaning Gender Column

In [48]:
data_frame["Gender"] = data_frame["Gender"].apply(categorize_gender)

Encountered unexpected string: "LLI"
Encountered unexpected string: "."

In [49]:
data_frame["Gender"].value_counts()

Gender
M    5098
F     637
Name: count, dtype: int64

### Cleaning Age Column

In [50]:
data_frame["Age"] = data_frame["Age"].apply(categorize_age)

Encountered unexpected string: "  "
Encountered unexpected string: "elderly"
Encountered unexpected string: "adult"
Encountered unexpected string: "(adult)"
Encountered unexpected string: "x"
Encountered unexpected string: ""middle-age""
Encountered unexpected string: "make line green"
Encountered unexpected string: ""young""
Encountered unexpected string: "f"
Encountered unexpected string: "young"
Encountered unexpected string: "a.m."
Encountered unexpected string: "young"

In [51]:
data_frame["Age"].value_counts()

Age
17.0    155
16.0    154
18.0    150
19.0    145
20.0    145
       ...
84.0      1
87.0      1
67.0      1
81.0      1
2.0       1
Name: count, Length: 81, dtype: int64

### Cleaning Fatality Column

In [52]:
data_frame["Fatal"] = data_frame["Fatal"].apply(categorize_fatality)

Encountered unexpected string: "2017"

In [53]:
data_frame["Fatal"].value_counts()

Fatal
N    4302
Y    1389
Name: count, dtype: int64

### Cleaning Time Column

In [54]:
data_frame["Time"] = data_frame["Time"].apply(categorize_time)

Encountered improper time string: "2 hours after Opperman".
Encountered improper time string: "FATAL  (Wire netting installed at local beaches after this incident.)".

In [55]:
data_frame["Time"].value_counts()

Time
Afternoon    1387
Morning       949
Evening       477
Night         122
Name: count, dtype: int64

### Cleaning Species Column

In [56]:
data_frame["Species"] = data_frame["Species"].apply(categorize_species)

Encountered unexpected string: "2 m shark"
Encountered unexpected string: "invalid incident"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "3.5 m shark"
Encountered unexpected string: "1.8 m shark"
Encountered unexpected string: "injury believed caused by an eel, not a shark"
Encountered unexpected string: "2m shark"
Encountered unexpected string: "small shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "8' shark"
Encountered unexpected string: "death may have been due to drowning"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "5' to 6' shark"
Encountered unexpected string: "shark involvement questionable"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "a small shark"
Encountered unexpected string: ""a small shark""
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "no shark invovlement"
Encountered unexpected string: "3m shark, probably a smooth hound"
Encountered unexpected string: "8' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "9' shark"
Encountered unexpected string: "shark involvement highly doubtful"
Encountered unexpected string: "no shark invovlement - it ws a publicity stunt"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "10' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "a small shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "6' to 8' shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "3' to 5' shark"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "said to involve an 8' shark but more likely damage caused by debris"
Encountered unexpected string: "3+ m shark"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "5' to 6' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "9' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "3' to 5' shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "juvenile shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "4' shark?"
Encountered unexpected string: "small shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "thought to involve a 3' to 4' shark, but shark involvement not confirmed"
Encountered unexpected string: "shark involvement not cofirmed"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "6' to 7' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "small shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "1m to 1.2 m shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "3- to 4-foot shark"
Encountered unexpected string: "shark involvement not cofirmed"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "3.5 to 4 m shark"
Encountered unexpected string: "2 m to  3 m shark"
Encountered unexpected string: "1.8 m shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "5 m shark"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: ""a small shark""
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "shark involvement prior to death still to be determined"
Encountered unexpected string: "shark involvement not confirmed & highly unlikely"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "2' shark"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "12' to 14' shark"
Encountered unexpected string: "1 m shark"
Encountered unexpected string: "8' to 10' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "7' shark"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "small shark"
Encountered unexpected string: "4' to 6' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "4' tp 5' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "1.8 metre shark"
Encountered unexpected string: "6' to 8' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "3m shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "cow shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "invalid"
Encountered unexpected string: "1m shark"
Encountered unexpected string: "4' to 6' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "a small shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: ""small sharks""
Encountered unexpected string: "2.5 m shark"
Encountered unexpected string: "10' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "2.5 m shark"
Encountered unexpected string: "2' to 3' shark"
Encountered unexpected string: "6' to 8' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "2m shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "3.5' to 4' shark"
Encountered unexpected string: "3.5' to 4' shark"
Encountered unexpected string: "4.5 m shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "14' to 18'shark"
Encountered unexpected string: "15' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "18" to 24" shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "a small shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "6' to 8' shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "7' to 8' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "8' to 10' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "10' to 12' shark"
Encountered unexpected string: "2 to 2.5 m shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "4' to 6' shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "4 m shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "1' to 2' shark"
Encountered unexpected string: "3 m to 4 m shark"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "1 m shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "2m shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "8' shark"
Encountered unexpected string: "1 m shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "20 to 30kg shark"
Encountered unexpected string: "20 to 30kg shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "14' shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "2 m to 3 m shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "6' to 8' shark"
Encountered unexpected string: "spurdog"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "invalid"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "shark involvement questionable"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement probable, but not confirmed"
Encountered unexpected string: "80 kg shark"
Encountered unexpected string: "5' to 8' shark"
Encountered unexpected string: "7' shark"
Encountered unexpected string: "2' to 3' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "2' to 3' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "thought to involve a cookie cutter shark"
Encountered unexpected string: "2.6 m shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "invalid"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "+3' shark"
Encountered unexpected string: "2' to 3' juvenile shark"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "3'  shark"
Encountered unexpected string: "2'  shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement prior to death not confirmed"
Encountered unexpected string: "4.5 to 5' shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "reported by media as shark attack, but shark involvement prior to death was not confirmed"
Encountered unexpected string: "shark involvement not confirmed; thought to be a barracuda bite"
Encountered unexpected string: "1.5' to 2' shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "a small shark"
Encountered unexpected string: "2.5' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "1 m shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "a small shark"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: ""a small shark""
Encountered unexpected string: "not a shark attack; it was a hoax"
Encountered unexpected string: "2.27 m shark"
Encountered unexpected string: "1.5 to 2 m shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "9.5' shark?"
Encountered unexpected string: "18" to 24" shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "2' to 3' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "2 m shark"
Encountered unexpected string: "questionable incident"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "2.5 m shark"
Encountered unexpected string: "10' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "6' to 8' shark"
Encountered unexpected string: ""a small shark""
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "4' to 5' shark"
Encountered unexpected string: "1.5 m shark"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "2 to 2.5 m shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "14' shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "2.4 m shark"
Encountered unexpected string: "24" to 30" shark"
Encountered unexpected string: "2.5 to 3 m shark"
Encountered unexpected string: "2 to 3 m shark"
Encountered unexpected string: "2 m to 3 m shark"
Encountered unexpected string: "1' to 4' shark"
Encountered unexpected string: "3' to 3.5' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "5' shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "3' shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "5 m shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "shark involvement not confirmed, injury may have been caused by a bluefish"
Encountered unexpected string: "2' to 3' shark"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "3 m, 600-kg shark"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "5' to 7' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "12' to 18' shark"
Encountered unexpected string: "12' shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "said to involve a 1.5 m shark"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "1.8 m shark"
Encountered unexpected string: "4' shark"
Encountered unexpected string: "6' shark"
Encountered unexpected string: "2' to 3' shark"
Encountered unexpected string: "2' shark"
Encountered unexpected string: "3 m shark"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "3' to 4' shark"
Encountered unexpected string: "2 m [6.75'] shark, 200-kg shark t"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "1.8 m [6'] shark"
Encountered unexpected string: "invalid"
Encountered unexpected string: "shark involvement not confirmed"
Encountered unexpected string: "shark involvement prior to death was not confirmed"
Encountered unexpected string: "3.5 m [11.5']shark"
Encountered unexpected string: "no shark involvement"
Encountered unexpected string: "[4.5' to 5'] shark"
Encountered unexpected string: "[4' to 5']"

In [57]:
data_frame["Species"].value_counts()

Species
Great White Shark         635
Tiger Shark               285
Bull Shark                208
Sand Tiger Shark           83
Copper Shark               77
Blacktip Shark             76
Shortfin Mako Shark        61
Nurse Shark                57
Wobbegong Shark            50
Hammerhead Shark           48
Spinner Shark              45
Blue Shark                 40
Lemon Shark                35
Oceanic Whitetip Shark     24
Grey Reef Shark            19
Sevengill shark            19
Sand Shark                 19
Unspecified Reef Shark     17
Caribbean Reef Shark       16
Dusky Shark                12
Spiny Dogfish              10
Sandbar Shark               8
Carpet Shark                8
Galapagos Shark             7
Porbeagle Shark             7
Basking Shark               7
Angel Shark                 6
Silky Shark                 4
Whitetip Reef Shark         4
Thresher Shark              4
Salmon Shark                3
Whale Shark                 3
Catshark                    3
Goblin Shark                2
Blackfin Shark              2
Leopard Shark               2
Silvertip Shark             2
Cookiecutter Shark          1
Port Jackson Shark          1
Longfin Mako Shark          1
Soupfin Shark               1
Sixgill shark               1
Name: count, dtype: int64

## Summary

### After Preprocessing

In [58]:
print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked     MEXICO           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location                 Activity  \
0                        Oceanside, San Diego County                  Surfing
1                     St. Simon Island, Glynn County  Wading in Shallow Water
2                                       Habush, Oahu                  Surfing
3                                 Arrawarra Headland                  Surfing
4                                           La Ticla                   Diving
5                                 Flat Rock, Ballina                  Surfing
6                              Piedade Beach, Recife                 Swimming
7  Lighhouse Point Park, Ponce Inlet, Volusia County                  Fishing
8                       Cocoa Beach, Brevard  County  Wading in Shallow Water
9                      Daytona Beach, Volusia County  Wading in Shallow Water

  Gender      Age Fatal       Time            Species
0      F     57.0     N    Evening  Great White Shark
1      F     11.0     N  Afternoon            Unknown
2      M     48.0     N    Morning            Unknown
3      M  Unknown     N    Unknown            Unknown
4      M  Unknown     N    Unknown        Tiger Shark
5      M  Unknown     N    Unknown            Unknown
6      M     18.0     Y  Afternoon        Tiger Shark
7      M     52.0     N    Unknown        Lemon Shark
8      M     15.0     N    Evening         Bull Shark
9      M     12.0     N  Afternoon            Unknown

In [59]:
data_frame.describe(include="all").T.fillna("—")

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Date,6302,5433,1957,11,—,—,—,—,—,—,—
Type,6298,6,Unprovoked,4595,—,—,—,—,—,—,—
Country,6252,212,USA,2229,—,—,—,—,—,—,—
Area,5847,825,Florida,1037,—,—,—,—,—,—,—
Location,5762,4108,"New Smyrna Beach, Volusia County",163,—,—,—,—,—,—,—
Activity,5758,10,Surfing,1384,—,—,—,—,—,—,—
Gender,5735,2,M,5098,—,—,—,—,—,—,—
Age,3456.0,—,—,—,27.291088,13.897882,1.0,17.0,24.0,35.0,87.0
Fatal,5691,2,N,4302,—,—,—,—,—,—,—
Time,2935,4,Afternoon,1387,—,—,—,—,—,—,—
Species,1913,42,Great White Shark,635,—,—,—,—,—,—,—